name: Supabase Request Every 5 Days

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  make-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send request to Supabase
      run: |
        curl -X POST \
          -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"key": "value"}' \
          https://lsohakpxtnsjxexmvdmj.supabase.co
