name: Supabase Request Every 5 Days

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  make-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send request to Supabase
      run: |
        curl 'https://lsohakpxtnsjxexmvdmj.supabase.co'
